apiVersion: v2
name: kubelet-stats-metrics
version: 0.1.4
appVersion: "0.1.4"
kubeVersion: ">=1.21.0-0"
description: Expose kubelet stats metrics to prometheus
home: https://github.com/careerpuck/kubelet-stats-metrics
keywords:
- kubernetes
- metrics
sources:
- https://github.com/careerpuck/kubelet-stats-metrics
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/careerpuck/kubelet-stats-metrics
